; Same as DDrawCompat.ini, but integer-scale the 4:3 framebuffer.
; More pillarbox, true pixels.

EnableDDrawCompat = on
LogLevel = info

FullscreenMode = borderless
DisplayResolution = desktop
DisplayAspectRatio = 4:3
DisplayFilter = integer
DisplayRefreshRate = desktop

BltFilter = point
RenderColorDepth = app
ColorKeyMethod = alphatest(1)
ResolutionScale = app(1)
ResolutionScaleFilter = point
TextureFilter = app
Antialiasing = off
PalettizedTextures = on
SoftwareDevice = rgb
AlternatePixelCenter = off

SupportedResolutions = native, 640x480, 800x600, 1024x768
SupportedRefreshRates = native

AltTabFix = keepvidmem(1)
VSync = on
FpsLimiter = msgloop(60)
PresentDelay = on(10)

CpuAffinity = all
CpuAffinityRotation = off
CompatFixes = nowindowborders
DpiAwareness = app
GdiInterops = all
WinVersionLie = 98
ForceD3D9On12 = off

DesktopColorDepth = 16
DesktopResolution = desktop
MousePollingRate = 125
MouseSensitivity = desktop(100)

ConfigHotKey = shift+f11
TerminateHotKey = ctrl+alt+end
